services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: 8487904580:AAGShz7eJmfZOvCDoCevK3t-o2DUe93VjFE
      - key: CHANNEL_USERNAME
        value: greatcvv小店
      - key: OWNER_URL
        value: https://t.me/greatcvvstore
      - key: OWNER_ID_1
        sync: false
      - key: OWNER_ID_2
        sync: false
      - key: WORKERS
        value: 16
